blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://tldraw.dev
    about: Looking for help with the tldraw SDK? Check out the docs.
  - name: Discord
    url: https://discord.tldraw.com
    about: Chat with the community and get help from other developers.
