name: i18n upload strings
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  upload:
    name: 'Upload latest strings'
    runs-on: ubuntu-latest
    environment: 'deploy-production'

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Upload i18n strings
        run: 'yarn i18n-upload-strings'
        env:
          LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
          LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
          LOKALISE_TEAM_ID: ${{ secrets.LOKALISE_TEAM_ID }}
          LOKALISE_CARD_ID: ${{ secrets.LOKALISE_CARD_ID }}
