name: End to end tests (perf)

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CI: 1
  PRINT_GITHUB_ANNOTATIONS: 1

defaults:
  run:
    shell: bash

jobs:
  build:
    name: 'End to end tests (perf)'
    timeout-minutes: 60
    runs-on: ubuntu-latest-16-cores-open

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run our setup
        uses: ./.github/actions/setup

      - name: Get installed Playwright version
        id: playwright-version
        run: |
          cd apps/examples
          yarn info @playwright/test --json > playwright.json
          echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./playwright.json').children.Version)")" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Check for Playwright browsers cache
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium chrome
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Run Playwright tests (perf)
        run: 'yarn e2e-perf'
        working-directory: apps/examples
        env:
          PERFORMANCE_ANALYTICS_ENABLED: true
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GIT_COMMIT: ${{ github.sha }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: apps/examples/playwright-report
          retention-days: 30
