name: Publish editor extensions

on:
  push:
    branches:
      - main
      - production

env:
  CI: 1
  PRINT_GITHUB_ANNOTATIONS: 1
defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish editor extensions
    environment: vsce publish
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency: vscode-extension-publish

    steps:
      - name: Generate GH token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.HUPPY_APP_ID }}
          private-key: ${{ secrets.HUPPY_APP_PRIVATE_KEY }}

      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ steps.generate_token.outputs.token }}

      - uses: ./.github/actions/setup

      - name: Build types
        run: yarn build-types

      - name: Get extension info from the marketplace
        working-directory: 'apps/vscode/extension'
        run: yarn get-info

      - name: Publish extension
        run: yarn tsx ./internal/scripts/publish-editor-extensions.ts
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
          TLDRAW_ENV: ${{ (github.ref == 'refs/heads/production' && 'production') || (github.ref == 'refs/heads/main' && 'staging') }}
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
